//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentsTrailersIAD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Campsite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campsite()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
       
        public int CampId { get; set; }
        public string Description { get; set; }

        [Required(ErrorMessage = "Please enter a valid price")]
        public int Price { get; set; }

        [Required(ErrorMessage = "Please enter a valid camp type")]
        public string Type { get; set; }

        [Required(ErrorMessage = "Please enter the number of people the campsite accomodates")]
        public int Accomodates { get; set; }

        [Required(ErrorMessage = "Please enter a valid campsite location")]
        public string Location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
