//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentsTrailersIAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecipitateMAX
    {
        public int PrecipitateMAXId { get; set; }
        public string MONTHS { get; set; }
        public decimal PrecipitationMAX { get; set; }
    }
}
