//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentsTrailersIAD.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Precipitate
    {
        
        public int PrecipitateId { get; set; }

        [DataMember(Name = "label")]
        public string MONTHS { get; set; }

        [DataMember(Name = "y")]
        public decimal Precipitation { get; set; }
    }
}
