//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TentsTrailersIAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int BookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Member Member { get; set; }
    }
}
